Major refactoring
CRVCIOIS/NLP pull request #39
Opened 2024-03-07 16:38 UTC by yuvve

Complete restructure of the code, with the purpose of increasing readability, decoupling and ease of testing.

The new structure is as follows:
- `classes/`: contains classes that are each responsible for a single feature.
- `adapters/`: contains classes that help communicate between other classes (i.e. fetch from SCB API and insert into DB).
- `pipeline/`: contains the scripts called by the pipeline - **this is the only place for modules that can be run directly** (i.e. those with main guards). Some pipeline scripts use a mix of classes and adapters, which is not ideal but I did not have time to fix it.
- `aux_methods/`: contains the persistent logger config.

Other changes:
- Persistent logging config that logs both to file and console (the logging level for both file and console can be set in the file).
- Removed unneeded dependencies from pipeline
- Incremented pipeline version to 0.0.2 
- Scraped data folder is now a variable
- Changed `SimpleScraper` to just `Scraper`
- `Scraper` now propagates "label:" instead of "org_nr:"

2024-03-07 21:23 UTC, simlar-0 requested changes
Great work! Some minor fixes

2024-03-07 21:23 UTC, simlar-0 commented on adapters/scb.py
> +            companies = self.mongo_client[Schema.DB][Schema.COMPANIES].find({"url": {"$regex": r"/\S"}})
This fetches all companies that have a URL, so param should be has_url?

2024-03-07 21:23 UTC, simlar-0 commented on adapters/extract.py
> +    """
Update docstring

2024-03-07 21:23 UTC, simlar-0 commented on adapters/scrape.py
> +    """
Update docstring

2024-03-07 21:23 UTC, simlar-0 commented on adapters/train.py
> +    """
Update docstring

2024-03-07 21:23 UTC, simlar-0 commented on pipeline/divide_dataset.py
> +            percentage_training_split: Annotated[int, typer.Argument()] = 10
Default should be 70%

2024-03-08 08:40 UTC, yuvve commented
> Great work! Some minor fixes

Thanks! I have fixed everything you mentioned and used that as an opportunity to improve the `no_url` / `has_url` parameters, so that they have now consistent behavior across both functions.

2024-03-08 12:52 UTC, merged